# ===================================================================
# GENERAL PROPERTIES
# ===================================================================
spring:
 main:
  banner-mode: off
 application:
  name: library-books-management
 server:
  port: 8080
 datasource:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/library
  username: root
  password:
 jpa:
  naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  hibernate.ddl-auto: none

# ===================================================================
# LOG PROPERTIES
# ===================================================================

logging:
 pattern:
  file: '[%X{data}%thread] [%X{X-B3-TraceId:-}] - %5p'
  console: "%p, %d{'yyyy-MM-dd HH:mm:ss,SSS',America/Mexico_City}, %C{1}:%M:%L, %X{mdc.uuid}, %m%n%ex{3}"
 level:
  mx.santander.logbook: DEBUG
  org:
   springframework.data: DEBUG
   hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE


# ===================================================================
# SWAGGER PROPERTIES
# ===================================================================
swagger:
 basePackage: mx.santander.logbook.management
 title: SERV-library-booksManagement
 descriptionApi: Gesti\u00F3n y administraci\u00F3n de los libros.
 version: 1.0.0
 nameDeveloper: Felipe Monz\u00F3n
 contactUrl: https://felipemonzon.github.io/
 emailDeveloper: felipemonzon2705@gmail.com
