# ===================================================================
# GENERAL PROPERTIES
# ===================================================================
spring:
 main:
  banner-mode: off
 application:
  name: library-users
 server:
  port: 8080
 datasource:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/library
  username: root
  password:
 jpa:
  naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  hibernate.ddl-auto: update

# ===================================================================
# LOG PROPERTIES
# ===================================================================
logging:
 pattern:
  file: '[%X{data}%thread] [%X{X-B3-TraceId:-}] - %5p'
  console: "%p, %d{'yyyy-MM-dd HH:mm:ss,SSS',America/Mexico_City}, %C{1}:%M:%L, %X{mdc.uuid}, %m%n%ex{3}"
 level:
  com.moontech.library.books.management: DEBUG
  org:
   springframework.data: DEBUG
   hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE


# ===================================================================
# URL ENDPOINTS
# ===================================================================
api:
  uri:
    basePath: /api
    domain:
      users: /users
    data:
      retrieve: /retrieve
      create: /create
      modified: /{id}
      search: /{search}
  interceptorPath: "/**"

# ===================================================================
# SWAGGER PROPERTIES
# ===================================================================
swagger:
 basePackage: com.moontech.library.books
 title: SERV-library-userDomain
 descriptionApi: Gesti\u00F3n y administraci\u00F3n de los usuarios.
 version: 1.0.0
 nameDeveloper: Felipe Monz\u00F3n
 contactUrl: https://felipemonzon.github.io/
 emailDeveloper: felipemonzon2705@gmail.com
